### ISSUE TITLE
error with ' and "

### ISSUE THREAD

**Issue by burbilog** [shervinemami/practice_speechrec_mappings#2]
The game offers '"' and refuses to accept correct answer:

~~~
[k'"'                                        L square  crunch  dub quote  
[k"
### WRONG! ######  [k'"' [k" ############ Tally: 32 correct, 9 wrong. ###################################
~~~

kubuntu 22.04 python 3.10.6

**Comment by shervinemami** [comment]
Hi @burbilog , you're right, it wasn't handling some special characters in Talon files well. I've updated the code just now, try with the latest code. If you still have a problem, give me your exact command line and talon "alphabet.csv" and "keys.py" files so I can debug it.

**Comment by burbilog** [comment]
yep, it's fixed now
